package hibernate;
// Generated 24-ene-2019 14:46:19 by Hibernate Tools 4.3.1.Final

/**
 * Gato generated by hbm2java
 */
public class Gato implements java.io.Serializable {

	private GatoId id;

	public Gato() {
	}

	public Gato(GatoId id) {
		this.id = id;
	}

	public GatoId getId() {
		return this.id;
	}

	public void setId(GatoId id) {
		this.id = id;
	}

}
