package hibernate;
// Generated 24-ene-2019 14:46:19 by Hibernate Tools 4.3.1.Final

/**
 * GatoId generated by hbm2java
 */
public class GatoId implements java.io.Serializable {

	private int id;
	private String nombre;
	private int edad;
	private String raza;
	private String color;
	private String observaciones;
	private boolean unyas;
	private char sexo;

	public GatoId() {
	}

	public GatoId(int id, String nombre, int edad, String raza, String color, boolean unyas, char sexo) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.raza = raza;
		this.color = color;
		this.unyas = unyas;
		this.sexo = sexo;
	}

	public GatoId(int id, String nombre, int edad, String raza, String color, String observaciones, boolean unyas,
			char sexo) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.raza = raza;
		this.color = color;
		this.observaciones = observaciones;
		this.unyas = unyas;
		this.sexo = sexo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public boolean isUnyas() {
		return this.unyas;
	}

	public void setUnyas(boolean unyas) {
		this.unyas = unyas;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GatoId))
			return false;
		GatoId castOther = (GatoId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& (this.getEdad() == castOther.getEdad())
				&& ((this.getRaza() == castOther.getRaza()) || (this.getRaza() != null && castOther.getRaza() != null
						&& this.getRaza().equals(castOther.getRaza())))
				&& ((this.getColor() == castOther.getColor()) || (this.getColor() != null
						&& castOther.getColor() != null && this.getColor().equals(castOther.getColor())))
				&& ((this.getObservaciones() == castOther.getObservaciones())
						|| (this.getObservaciones() != null && castOther.getObservaciones() != null
								&& this.getObservaciones().equals(castOther.getObservaciones())))
				&& (this.isUnyas() == castOther.isUnyas()) && (this.getSexo() == castOther.getSexo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + this.getEdad();
		result = 37 * result + (getRaza() == null ? 0 : this.getRaza().hashCode());
		result = 37 * result + (getColor() == null ? 0 : this.getColor().hashCode());
		result = 37 * result + (getObservaciones() == null ? 0 : this.getObservaciones().hashCode());
		result = 37 * result + (this.isUnyas() ? 1 : 0);
		result = 37 * result + this.getSexo();
		return result;
	}

}
