package hibernate;
// Generated 24-ene-2019 14:46:19 by Hibernate Tools 4.3.1.Final

/**
 * PerroId generated by hbm2java
 */
public class PerroId implements java.io.Serializable {

	private int id;
	private String nombre;
	private int edad;
	private String raza;
	private String color;
	private String observaciones;
	private String pelaje;
	private boolean peligrosa;
	private char sexo;

	public PerroId() {
	}

	public PerroId(int id, String nombre, int edad, String raza, String color, String pelaje, boolean peligrosa,
			char sexo) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.raza = raza;
		this.color = color;
		this.pelaje = pelaje;
		this.peligrosa = peligrosa;
		this.sexo = sexo;
	}

	public PerroId(int id, String nombre, int edad, String raza, String color, String observaciones, String pelaje,
			boolean peligrosa, char sexo) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.raza = raza;
		this.color = color;
		this.observaciones = observaciones;
		this.pelaje = pelaje;
		this.peligrosa = peligrosa;
		this.sexo = sexo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getPelaje() {
		return this.pelaje;
	}

	public void setPelaje(String pelaje) {
		this.pelaje = pelaje;
	}

	public boolean isPeligrosa() {
		return this.peligrosa;
	}

	public void setPeligrosa(boolean peligrosa) {
		this.peligrosa = peligrosa;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerroId))
			return false;
		PerroId castOther = (PerroId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& (this.getEdad() == castOther.getEdad())
				&& ((this.getRaza() == castOther.getRaza()) || (this.getRaza() != null && castOther.getRaza() != null
						&& this.getRaza().equals(castOther.getRaza())))
				&& ((this.getColor() == castOther.getColor()) || (this.getColor() != null
						&& castOther.getColor() != null && this.getColor().equals(castOther.getColor())))
				&& ((this.getObservaciones() == castOther.getObservaciones())
						|| (this.getObservaciones() != null && castOther.getObservaciones() != null
								&& this.getObservaciones().equals(castOther.getObservaciones())))
				&& ((this.getPelaje() == castOther.getPelaje()) || (this.getPelaje() != null
						&& castOther.getPelaje() != null && this.getPelaje().equals(castOther.getPelaje())))
				&& (this.isPeligrosa() == castOther.isPeligrosa()) && (this.getSexo() == castOther.getSexo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + this.getEdad();
		result = 37 * result + (getRaza() == null ? 0 : this.getRaza().hashCode());
		result = 37 * result + (getColor() == null ? 0 : this.getColor().hashCode());
		result = 37 * result + (getObservaciones() == null ? 0 : this.getObservaciones().hashCode());
		result = 37 * result + (getPelaje() == null ? 0 : this.getPelaje().hashCode());
		result = 37 * result + (this.isPeligrosa() ? 1 : 0);
		result = 37 * result + this.getSexo();
		return result;
	}

}
