package hibernate;
// Generated 24-ene-2019 14:46:19 by Hibernate Tools 4.3.1.Final

/**
 * Perro generated by hbm2java
 */
public class Perro implements java.io.Serializable {

	private PerroId id;

	public Perro() {
	}

	public Perro(PerroId id) {
		this.id = id;
	}

	public PerroId getId() {
		return this.id;
	}

	public void setId(PerroId id) {
		this.id = id;
	}

}
